# Generated by Django 5.2 on 2025-04-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
